// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250825000546_NotificationTable")]
    partial class NotificationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.entities.Admins", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanDo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("API.entities.EmailToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("EmailTokens");
                });

            modelBuilder.Entity("API.entities.Photos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("publicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrainnerId")
                        .IsUnique();

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("ClassesClients", b =>
                {
                    b.Property<int>("ClassesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClassesId", "ClientsId");

                    b.HasIndex("ClientsId");

                    b.ToTable("ClassesClients");
                });

            modelBuilder.Entity("api.entities.Appointments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdminId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClassesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("clientcase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("clientcomment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ClassesId");

                    b.HasIndex("ClientId");

                    b.HasIndex("TrainnerId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("api.entities.Classes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("api.entities.ClientTrainner", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClientId", "TrainnerId");

                    b.HasIndex("TrainnerId");

                    b.ToTable("ClientTrainners");
                });

            modelBuilder.Entity("api.entities.Clients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdminId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("api.entities.ClientsPhotos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainnersId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("publicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("TrainnersId");

                    b.ToTable("ClientsPhotos");
                });

            modelBuilder.Entity("api.entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("api.entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrainnerId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("api.entities.TrainnerClass", b =>
                {
                    b.Property<int>("TrainnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrainnerId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("TrainnerClasses");
                });

            modelBuilder.Entity("api.entities.Trainners", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdminId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("TrainnerPrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Trainners");
                });

            modelBuilder.Entity("API.entities.EmailToken", b =>
                {
                    b.HasOne("api.entities.Clients", "Client")
                        .WithOne("EmailToken")
                        .HasForeignKey("API.entities.EmailToken", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("API.entities.Photos", b =>
                {
                    b.HasOne("api.entities.Trainners", "Trainners")
                        .WithOne("Photos")
                        .HasForeignKey("API.entities.Photos", "TrainnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainners");
                });

            modelBuilder.Entity("ClassesClients", b =>
                {
                    b.HasOne("api.entities.Classes", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.entities.Clients", null)
                        .WithMany()
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.entities.Appointments", b =>
                {
                    b.HasOne("API.entities.Admins", "Admins")
                        .WithMany("Appointments")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.entities.Classes", null)
                        .WithMany("Appointments")
                        .HasForeignKey("ClassesId");

                    b.HasOne("api.entities.Clients", "Clients")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.entities.Trainners", "Trainners")
                        .WithMany("Appointments")
                        .HasForeignKey("TrainnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admins");

                    b.Navigation("Clients");

                    b.Navigation("Trainners");
                });

            modelBuilder.Entity("api.entities.ClientTrainner", b =>
                {
                    b.HasOne("api.entities.Clients", "Client")
                        .WithMany("ClientTrainners")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.entities.Trainners", "Trainner")
                        .WithMany("ClientTrainners")
                        .HasForeignKey("TrainnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Trainner");
                });

            modelBuilder.Entity("api.entities.Clients", b =>
                {
                    b.HasOne("API.entities.Admins", "Admins")
                        .WithMany("Clients")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admins");
                });

            modelBuilder.Entity("api.entities.ClientsPhotos", b =>
                {
                    b.HasOne("api.entities.Appointments", "Appointments")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.entities.Clients", "Clients")
                        .WithMany("ClientsPhotos")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.entities.Trainners", "Trainners")
                        .WithMany("ClientsPhotos")
                        .HasForeignKey("TrainnersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointments");

                    b.Navigation("Clients");

                    b.Navigation("Trainners");
                });

            modelBuilder.Entity("api.entities.Schedule", b =>
                {
                    b.HasOne("api.entities.Trainners", "Trainners")
                        .WithMany("Schedules")
                        .HasForeignKey("TrainnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainners");
                });

            modelBuilder.Entity("api.entities.TrainnerClass", b =>
                {
                    b.HasOne("api.entities.Classes", "Class")
                        .WithMany("TrainnerClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.entities.Trainners", "Trainner")
                        .WithMany("TrainnerClasses")
                        .HasForeignKey("TrainnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Trainner");
                });

            modelBuilder.Entity("api.entities.Trainners", b =>
                {
                    b.HasOne("API.entities.Admins", "Admins")
                        .WithMany("Trainners")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admins");
                });

            modelBuilder.Entity("API.entities.Admins", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Clients");

                    b.Navigation("Trainners");
                });

            modelBuilder.Entity("api.entities.Classes", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("TrainnerClasses");
                });

            modelBuilder.Entity("api.entities.Clients", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ClientTrainners");

                    b.Navigation("ClientsPhotos");

                    b.Navigation("EmailToken")
                        .IsRequired();
                });

            modelBuilder.Entity("api.entities.Trainners", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ClientTrainners");

                    b.Navigation("ClientsPhotos");

                    b.Navigation("Photos")
                        .IsRequired();

                    b.Navigation("Schedules");

                    b.Navigation("TrainnerClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
